### PR TITLE
Restyling and eslint

### PR DESCRIPTION
**Pull request by plusk**
Did some restyling, main talking points include basically switching over to a "light" style, and using a whole lot less orange.

Actually running eslint proved challenging due to some weird interactions with our code, leaving it to @Aborysa 

Old design:
screenshot from 2017-01-16 11-27-54

screenshot from 2017-01-16 11-28-08

New design:
screenshot from 2017-01-16 11-23-36

screenshot from 2017-01-16 11-23-54

Note that the design is by no means final, especially the dividers and the status field (which I've come to think of as kind of obnoxious design-wise). I'm also not married to that shade of blue, indigo might work better. I might've gone overboard on the anti-orange though, because at this point there is pretty much no orange on the page.

### CODE REVIEW

**Comment by arwassa** [comment]
Hmm will take a look at it.

**Comment by OptimusCrime** [comment]
PR should include print screens

**Comment by plusk** [comment]
@OptimusCrime print screens included now, will remember for the future

**Comment by myth** [comment]
"Registrerings dato" -> "Registreringsdato". Datetime format should be in Norwegian standard as well. Other than that, good job! :+1:

**Pull request merged**
